### ISSUE TITLE
Object Storage Service

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/object-storage-service#100]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/doc/source/index.rst

The API Reference associated to the SWIFT can be removed. The cluster is dismantled resp. deconstructed. So we can remove the documentation.

BR,
Daniel

**Comment by dsabelni** [comment]
Hi @DanielTSI ! Thanks for the hint, we'll notify the vendor so that the SWIFT documentation was removed.

**Comment by dsabelni** [comment]
The API Reference (Swift) is no longer shown on the Object Storage Service index page:
![image](https://github.com/user-attachments/assets/97e0836e-46b6-4beb-aae2-0bb549a0c4a4)
