### ISSUE TITLE
Link in OBS console - edit lifecycle rules - learn how link is not working 

### ISSUE THREAD

**Issue by marmulle2** [opentelekomcloud-docs/object-storage-service#41]
Issue is related to [STO-13339](https://jira.tsi-dev.otc-service.com/browse/STO-13339)
INCIDENT: Link to HC3.0 in OTC console does not work

**Comment by marmulle2** [comment]
@wangjianyu13 can you please check?

**Comment by dsabelni** [comment]
Fixed
