### ISSUE TITLE
Parallel File System

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/object-storage-service#48]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/umn/source/service_overview/basic_concepts/parallel_file_system.rst

We need a link to the PFS manual
https://docs.otc.t-systems.com/object-storage-service/parallel-file-system/

**Comment by dsabelni** [comment]
Thank you for your ticket! Internal ticket was created for this issue, when there are updates they'll be posted here.

**Comment by dsabelni** [comment]
Fixed - please see https://docs.otc.t-systems.com/object-storage-service/umn/service_overview/basic_concepts/parallel_file_system.html
