### ISSUE TITLE
Deleting Objects

### ISSUE THREAD

**Issue by Nikolai-Maier** [opentelekomcloud-docs/object-storage-service#54]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/api-ref/source/apis/operations_on_objects/deleting_objects.rst

There should be a chapter for "Restore deleted object" (Works only when versioning is enabled)
There should be a chapter for "Restore deleted objects" (Works only when versioning is enabled)
For customers it would be helpful to have the description, and a script and an example for the parameters.

e.g. AWS https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManagingDelMarkers.html

For questions contact nikolai.maier@t-systems.com

**Comment by dsabelni** [comment]
Thank you for your ticket! Internal ticket was created for this issue, when there are updates they'll be posted here.

**Comment by dsabelni** [comment]
Info was added to the page https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/operations_on_objects/deleting_an_object.html

> To delete an object of a specified version, the versionId parameter can be used to specify the desired version.
> To restore a deleted object, you need to specify the delete marker version in the versionId parameter when deleting it.

Also two new sample requests and responses were added: _Specifying versionId to Delete a Specific Object Version_ and _Specifying versionId to Delete a Delete Marker_
