### ISSUE TITLE
Uploading a File

### ISSUE THREAD

**Issue by tischrei** [opentelekomcloud-docs/object-storage-service#62]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/umn/source/obs_console_operation_guide/managing_objects/uploading_a_file.rst

If you are looking as a customer to find OBS uploader tool, there is no downlink link or anything else provided. This should be better described from customer point of view.

**Comment by dsabelni** [comment]
Hello tischrei! These are the tools that are supported at this moment:
- OBS Browser+
- obsutil
Can you please check if you're talking about any of those two tools?

**Comment by tischrei** [comment]
I mean the link to the OBS Browser+.
I am missing a link to the application from the OBS user manual. I struggled a lot until I found it on the web UI which is not that clearly visible.

**Comment by dsabelni** [comment]
There is a section called OBS Browser Operation Guide in the User Guide, in this section we have a page https://docs.otc.t-systems.com/object-storage-service/umn/obs_browser_operation_guide/getting_started/downloading_obs_browser.html - it doesn't have the link to the application itself but it contains info about where to find it. Would it be sufficient?

**Comment by tischrei** [comment]
I saw this helpcenter page but if you are in your bucket, you don't see any link from there and that was a bit strange for me.
So a screenshot would be nice to clarify the position of the download link and that you have to go up instead staying in your own bucket. The description of "click the OBS Browser package link on the homepage of OBS Console" can be anywhere and is not clear from my point of view.

**Comment by dsabelni** [comment]
Thank you for your feedback, an internal ticket has been created.

**Comment by tischrei** [comment]
cool thx

**Comment by dsabelni** [comment]
Now links for downloading OBS Browser+ are also available in the tool guide document: https://docs.otc.t-systems.com/object-storage-service/tool-guide/downloading_obs_browser.html
