### ISSUE TITLE
API Overview

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/object-storage-service#77]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/api-ref/source/api_overview.rst

WORM API is missing in overview. In the list of APIs it is made available

https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/advanced_bucket_settings/configuring_a_default_worm_policy_for_a_bucket.html#obs-04-0167
https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/advanced_bucket_settings/obtaining_the_default_worm_policy_of_a_bucket.html#obs-04-0168

**Comment by dsabelni** [comment]
Hello @DanielTSI , thank you for highlighting this issue! Corresponding internal ticket has been created.

**Comment by dsabelni** [comment]
The issue has been fixed - now API overview page https://docs.otc.t-systems.com/object-storage-service/api-ref/api_overview.html contains links to:

- [Configuring a Default WORM Policy for a Bucket](https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/advanced_bucket_settings/configuring_a_default_worm_policy_for_a_bucket.html#obs-04-0167)
- [Obtaining the Default WORM Policy of a Bucket](https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/advanced_bucket_settings/obtaining_the_default_worm_policy_of_a_bucket.html#obs-04-0168)
- [Configuring WORM Retention for an Object](https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/operations_on_objects/configuring_worm_retention_for_an_object.html#obs-04-0166)
