### ISSUE TITLE
Cross-Region Replication Overview

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/object-storage-service#86]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/umn/source/obs_console_operation_guide/cross-region_replication/cross-region_replication_overview.rst

There seems to be an issue with the limiations. Its mentioned in the section that you cannot replicate existing objects.
But this is possible and available,
![image](https://github.com/opentelekomcloud-docs/object-storage-service/assets/126478870/6a0cba20-c120-462c-b982-7d131ae05633)
I did an own separate test and can confim this.
This feature is even available via console and API.

BR,
Daniel

**Comment by dsabelni** [comment]
Hello @DanielTSI ! Can you please provide some more information about the part of the documentation that mentions that existing objects cannot be replicated? I see this part about the objects that can be replicated:

> Historical objects in a bucket (The function of synchronizing existing objects must be enabled.)

I've retested it and it seems to be working correctly as described in the document: if the Synchronize Existing Objects option in the CRR rule is enabled - objects that existed before the rule was applied are replicated; otherwise - those objects are not replicated.

**Comment by dsabelni** [comment]
Now I see the incorrect line - it is located in the Limitations and Constraints section:

> Objects cannot be copied to the destination bucket if they are uploaded before cross-region replication is enabled.

I agree, this is incorrect. I'll request that this line is removed.

**Comment by dsabelni** [comment]
> The issue is that there is a section called Limitation/Restriction. This hast two notes explaining that existing Objects cannot be synchronized.

I've reread it and I can see only one such line:

> Objects cannot be copied to the destination bucket if they are uploaded before cross-region replication is enabled.

Please inform me if I'm missing some other incorrect line.

**Comment by DanielTSI** [comment]
You are right. I rechecked the content.

Br,
Daniel

sent with Corporate Mobile Service

Am 26.02.2024 16:03 schrieb Dmitrii Sabelnikov ***@***.***>:

The issue is that there is a section called Limitation/Restriction. This hast two notes explaining that existing Objects cannot be synchronized.

I've reread it and I can see only one such line:

Objects cannot be copied to the destination bucket if they are uploaded before cross-region replication is enabled.

Please inform me if I'm missing some other incorrect line.

**Comment by dsabelni** [comment]
The wrong line fix was provided and will be published with the next UMN documentation update.

**Comment by dsabelni** [comment]
The line "Objects cannot be copied to the destination bucket if they are uploaded before cross-region replication is enabled." was removed from the page https://docs.otc.t-systems.com/object-storage-service/umn/obs_console_operation_guide/cross-region_replication/cross-region_replication_overview.html
