### ISSUE TITLE
About Parallel File System

### ISSUE THREAD

**Issue by DanielTSI** [opentelekomcloud-docs/object-storage-service#92]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/doc/parallel-file-system/source/introduction/about_parallel_file_system.rst

Its mentioned that the PFS can support "Terabytes of bandwidth and can handle millions of IOPS". this is not correct.
Can we replace this with "high Bandwidth" and "huge amount of IOPS". We should not specify numbers. I receive complains by customers as this is not correct.

**Comment by dsabelni** [comment]
Hello @DanielTSI , thank you for your request, we'll update the documentation.

**Comment by dsabelni** [comment]
The text was updated.
