### ISSUE TITLE
Application Scenarios, please check

### ISSUE THREAD

**Issue by Thies76** [opentelekomcloud-docs/object-storage-service#98]
Issue on page:        https://github.com/opentelekomcloud-docs/object-storage-service/blob/main/doc/parallel-file-system/source/introduction/application_scenarios.rst

Dear Team,

please can you have a look at the scenarios in context with the following issue: INC04342848 

Thank you!

**Comment by dsabelni** [comment]
Hello,

Thank you for your request! Waiting for a statement from vendor regarding this issue.

**Comment by dsabelni** [comment]
Application Scenarios page was updated - https://docs.otc.t-systems.com/object-storage-service/parallel-file-system/introduction/application_scenarios.html
